services:
    Enhavo\Bundle\BackupBundle\Notification\Type\NotificationType:
        tags:
            - { name: enhavo_backup.notification }

    Enhavo\Bundle\BackupBundle\Notification\Type\EmailNotificationType:
        arguments:
            - '@Enhavo\Bundle\AppBundle\Mailer\MailerManager'
            - '@enhavo_app.template.manager'
        tags:
            - { name: enhavo_backup.notification }
